# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 36dd3632c506e3357d87e6cdc2cb5c735385b2a5125d2e8b937f79cb5f875bc7e061b22a34057bf41cce90e95e26d0ea933e7cd9582389ecb372ee26b42ec3fa

test:
  secret_key_base: e5867e4e23916615f26e284c234ccbcedac7685c0d8115ce93c00063f4df2f5e1f1f54fbe38b8fce56e13cd684e76e2bad829854f779e3969752de6d1d09841d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
